package com.webizon.storage.model;

/**
 * Logical purpose of a {@link FileAsset}.
 *
 * <p>Each purpose maps to exactly one MinIO bucket and to a distinct
 * set of defaults: max size, allowed content types, presigned-URL
 * TTLs, and which roles may initiate uploads. Centralising those
 * defaults on the enum keeps {@code StorageService} free of sprawling
 * switch blocks.
 *
 * <p>The enum is also persisted as a string in
 * {@code file_assets.purpose}, so reordering values is safe but
 * renaming them requires a migration.
 */
public enum AssetPurpose {
    /** Event cover image shown on the landing page. */
    COVER,
    /** Downloadable material attached to a FILE-type CTA. */
    CTA_FILE,
    /** Post-event MP4 recording used as the source for AUTO replays. */
    RECORDING,
    /** Tenant billing PDF generated by the billing module. */
    INVOICE
}
