-- ============================================================
-- V019: AI-powered lead scoring table
--
-- Stores Claude API classification results: hot/warm/cold
-- plus reasoning, recommended actions, and confidence scores.
-- One row per (session, profile) pair — upserted after each
-- session ends or on-demand from admin panel.
-- ============================================================

CREATE TABLE IF NOT EXISTS ai_lead_scores (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID        NOT NULL REFERENCES tenants(id),
    event_id        UUID        NOT NULL REFERENCES events(id),
    session_id      UUID        NOT NULL REFERENCES sessions(id),
    profile_id      UUID        NOT NULL REFERENCES users(id),

    -- Rule-based score (sum of lead_signals for this session)
    rule_score      INT         NOT NULL DEFAULT 0,

    -- AI classification
    classification  VARCHAR(16) NOT NULL DEFAULT 'cold',   -- hot / warm / cold
    confidence      REAL        NOT NULL DEFAULT 0.0,       -- 0.0 – 1.0
    reasoning       TEXT,                                    -- AI explanation
    recommended_action TEXT,                                 -- what sales should do
    follow_up_hours INT,                                     -- when to contact

    -- Model metadata
    ai_model        VARCHAR(64),                             -- claude-sonnet-4-6 etc.
    prompt_tokens   INT,
    completion_tokens INT,

    -- Behavioral summary (stored for audit / re-scoring)
    watch_duration_seconds  INT     NOT NULL DEFAULT 0,
    watch_percent           REAL    NOT NULL DEFAULT 0.0,
    chat_messages_count     INT     NOT NULL DEFAULT 0,
    cta_clicks_count        INT     NOT NULL DEFAULT 0,
    cta_details             JSONB   NOT NULL DEFAULT '[]'::jsonb,
    returned_for_auto       BOOLEAN NOT NULL DEFAULT false,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ai_lead_scores_session_profile_uniq
        UNIQUE (session_id, profile_id)
);

-- Indexes for common read patterns
CREATE INDEX ai_lead_scores_session_idx
    ON ai_lead_scores (session_id, classification);
CREATE INDEX ai_lead_scores_profile_idx
    ON ai_lead_scores (profile_id, created_at DESC);
CREATE INDEX ai_lead_scores_tenant_idx
    ON ai_lead_scores (tenant_id);
CREATE INDEX ai_lead_scores_classification_idx
    ON ai_lead_scores (tenant_id, classification, confidence DESC);

-- RLS
ALTER TABLE ai_lead_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_lead_scores FORCE ROW LEVEL SECURITY;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'ai_lead_scores' AND policyname = 'ai_lead_scores_tenant_isolation'
    ) THEN
        CREATE POLICY ai_lead_scores_tenant_isolation ON ai_lead_scores
            USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::UUID);
    END IF;
END $$;

-- Extend LeadSignalType enum support — add AI signal types
-- (the Java enum already has these; this just documents the data-level contract)
COMMENT ON TABLE ai_lead_scores IS
    'AI-powered lead classification per (session, profile). '
    'Generated by Claude API after session ends. '
    'Rule-based score from lead_signals is stored alongside AI classification for comparison.';
